# Generated by Django 5.1.6 on 2025-04-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('summary', models.TextField()),
                ('degree', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('previous_experience', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
